# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MedicineReminder' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for MedicineReminder
    pod "TextFieldEffects"
    pod 'MBProgressHUD'
    pod 'IQKeyboardManagerSwift'
    

    target 'MedicineReminderTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'MedicineReminderUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
